### ISSUE TITLE
Try NCL_scan

### ISSUE THREAD

**Issue by kopardev** [CCBR/CCBR_circRNA_DAQ#40]
Available [here](https://github.com/TreesLab/NCLscan).

**Comment by kopardev** [comment]
Errors out with 
```
Traceback (most recent call last):
  File "test.py", line 109, in <module>
    add_gene_name(args.result_tmp_file, args.gene_anno, args.output)
  File "test.py", line 10, in add_gene_name
    gene_name_dict = get_gene_name_dict(anno_file)
  File "test.py", line 48, in get_gene_name_dict
    raise Exception('No "gene_name" field!')
Exception: No "gene_name" field!
```

**Comment by kopardev** [comment]
`/data/kopardevn/SandBox/NCLscan-1.7.0/bin/get_gene_name.py` script requires "exon" line to include "gene_name" attribute.. which may be missing in custom-made documentation eg. Viral GTF... Explore [pygtf](https://github.com/chengcz/pyGTF) to make a script to fix the viral GTF to include "gene_name".

**Comment by kopardev** [comment]
Fixed with [fix_gtfs.py](https://github.com/CCBR/CCBR_circRNA_DAQ/blob/6791801c389c73b25d1603b8bb128374517c060f/workflow/scripts/fix_gtfs.py)

**Comment by kopardev** [comment]
NCL is working in v0.7.0

**Comment by kopardev** [comment]
Running NCLscan on our HPC runs into memory issues. The dashboard plots look like this:
<img width="793" alt="image" src="https://user-images.githubusercontent.com/1882209/207998857-bdcd4772-68c2-4823-afc0-2cdee2d0c175.png">

Issue reported to author..[here](https://github.com/TreesLab/NCLscan/issues/30)
