### ISSUE TITLE
DCC error

### ISSUE THREAD

**Issue by kopardev** [CCBR/CCBR_circRNA_DAQ#43]
Getting the following DCC error
```bash
+ DCC @/gpfs/gsfs12/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.7.0/samples_1/results/C_MRC5_Infected_3d_R2/DCC/samples$
eet.txt --temp /lscratch/53799899/c9067538-72d8-4e7c-8f23-ade1389ca168 --threads 32 --detect -ss --annotation /gpfs/gsfs12/users/$
iegelbauer_lab/circRNADetection/circRNA_daq_v0.7.0/samples_1/ref/ref.gtf --chrM --rep_file /data/Ziegelbauer_lab/resources/fastas$
gtfs/hg38.repeats.gtf --refseq /gpfs/gsfs12/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.7.0/samples_1/ref/ref.fa --PE-i$
dependent -mt1 @/gpfs/gsfs12/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.7.0/samples_1/results/C_MRC5_Infected_3d_R2/DC$
/mate1.txt -mt2 @/gpfs/gsfs12/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.7.0/samples_1/results/C_MRC5_Infected_3d_R2/D$
C/mate2.txt
Traceback (most recent call last):
  File "/data/CCBR_Pipeliner/db/PipeDB/Conda/envs/DCC/bin/DCC", line 11, in <module>
    load_entry_point('DCC==0.5.0', 'console_scripts', 'DCC')()
  File "build/bdist.linux-x86_64/egg/DCC/main.py", line 492, in main
  File "build/bdist.linux-x86_64/egg/DCC/main.py", line 680, in findCircSkipJunction
  File "build/bdist.linux-x86_64/egg/DCC/Circ_nonCirc_Exon_Match.py", line 281, in findcircAdjacent
  File "build/bdist.linux-x86_64/egg/DCC/Circ_nonCirc_Exon_Match.py", line 222, in getAdjacent
ValueError: invalid literal for int() with base 10: '104404_104424_transcript_1'
```

**Comment by kopardev** [comment]
ref gtf has the following line 
```bash
3016481:NC_006273.2        RefSeq  tanscript        104404  104424  .       +       .       gene_id "NC_006273.2:104404_104424"; gene_name "NC_006273.2:104404_104424; gene_biotype "ncRNA"; transcript_id "NC_006273.2:104404_104424_transcript_1"; transcript_name "NC_006273.2:104404_104424_transcipt_1"; transcript_type "ncRNA"; gbkey "ncRNA"; inference "ab initio prediction:miRBase:rel16"; product "hcmv-miR-UL70-5p";
```
It does not seems to like the transcript_id format in column 9
`transcript_id "NC_006273.2:104404_104424_transcript_1"`
