### ISSUE TITLE
DCC error: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by kopardev** [CCBR/CCBR_circRNA_DAQ#54]
```
+ DCC @/vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_032223/results/iSLK_BAC16_72hpi_R1/DCC/samplesheet.txt --temp /lscratch/61412431/9e8ae03f-5978-4f36-8fbc-5ce64779c11f/DCC --threads 32 --detect --gene --bam /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_032223/results/iSLK_BAC16_72hpi_R1/STAR2p/iSLK_BAC16_72hpi_R1_p2.bam -ss --annotation /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_032223/ref/ref.gtf --chrM -G --rep_file /data/Ziegelbauer_lab/resources/fastas_gtfs/hg38.repeats.gtf --refseq /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_032223/ref/ref.fa --PE-independent -mt1 @/vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_032223/results/iSLK_BAC16_72hpi_R1/DCC/mate1.txt -mt2 @/vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_032223/results/iSLK_BAC16_72hpi_R1/DCC/mate2.txt
[W::hts_idx_load3] The index file is older than the data file: /vf/users/Ziegelbauer_lab/circRNADetection/circRNA_daq_v0.8.x/samples_3_032223/results/iSLK_BAC16_72hpi_R1/STAR2p/iSLK_BAC16_72hpi_R1_p2.bam.csi
Traceback (most recent call last):
  File "/data/CCBR_Pipeliner/db/PipeDB/Conda/envs/DCC/bin/DCC", line 11, in <module>
    load_entry_point('DCC==0.5.0', 'console_scripts', 'DCC')()
  File "build/bdist.linux-x86_64/egg/DCC/main.py", line 492, in main
  File "build/bdist.linux-x86_64/egg/DCC/main.py", line 680, in findCircSkipJunction
  File "build/bdist.linux-x86_64/egg/DCC/Circ_nonCirc_Exon_Match.py", line 281, in findcircAdjacent
  File "build/bdist.linux-x86_64/egg/DCC/Circ_nonCirc_Exon_Match.py", line 222, in getAdjacent
ValueError: invalid literal for int() with base 10: '127997-129368_transcript_1'
```

**Comment by kopardev** [comment]
Total: 34
completed: 23
failed: 11

**Comment by kopardev** [comment]
All 11 have the same error:
`ValueError: invalid literal for int() with base 10: '127997-129368_transcript_1'`

**Comment by kopardev** [comment]
This could be because of `note` key in the ref.gtf for the last gene on the virus. The value of note also has a `;` which is the key-value pair delimiter in GTF. May be need to use the `ref.fixed.gtf` which are originally generated for nclscan. Here is the same line in `ref.gtf`
```
NC_009333.1	RefSeq	transcript	127997	129368	.	+	.	gene_id "NC_009333.1:127997-129368"; gene_name "NC_009333.1:127997-129368"; transcript_id "NC_009333.1:127997-129368_transcript_1"; transcript_name "NC_009333.1:127997-129368_transcript_1"; gbkey "mRNA"; note "K14, ORF74; polyA_site not reported"; gene_biotype "mRNA"; transcript_type "mRNA";
```
and `ref.fixed.gtf`:
```
NC_009333.1	RefSeq	transcript	127997	129368	.	+	.	transcript_type "mRNA"; gene_id "NC_009333.1:127997-129368"; gbkey "mRNA"; transcript_name "NC_009333.1:127997-129368_transcript_1"; gene_biotype "mRNA"; transcript_id "NC_009333.1:127997-129368_transcript_1"; gene_name "NC_009333.1:127997-129368";
```

**Comment by kopardev** [comment]
Testing if error disappears if we use `ref.fixed.gtf` for running DCC

**Comment by kopardev** [comment]
Error disappears! ... Need to force the use of `ref.fixed.gtf` for all rules!!

**Comment by kopardev** [comment]
Use commit 0a097f8 or later
